#ifndef ENUMS_H
#define ENUMS_H

enum EdgeNames { OPPOSITE_BISECTOR, BISECTOR, V1, V2, V3, V4 };
enum ZoneNames { STRONG_IDENTIFICATION, IDENTIFICATION, RECOGNITION, OBSERVATION, DETECTION, MONITORING, DEAD_ZONE };

#endif // ENUMS_H
